package org.tohu.generator

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.tohu.MultipleChoiceQuestion;
import org.tohu.MultipleChoiceQuestion.PossibleAnswer;


rule "Possible_Answers_are_NULL_59"
dialect "java"
	when
		$mcq : MultipleChoiceQuestion ( id == "MCQ-4", possibleAnswers == null )  
	then
		org.tohu.MultipleChoiceQuestion.PossibleAnswer[] answers = new PossibleAnswer[1];
		answers[0] = new PossibleAnswer("Test-1", "Answer to Test-1");		
		$mcq.setPossibleAnswers(answers);		
		update( $mcq );		
end

rule "Possible_Answers_not_NULL_59"
no-loop
dialect "java"
	when
		$mcq : MultipleChoiceQuestion ( id == "MCQ-4", $pas : possibleAnswers != null, possibleAnswersAsString not matches ".*Test-2.*")
	then
		PossibleAnswer newAnswer = new PossibleAnswer("Test-2", "Answer to Test-2");
		List<PossibleAnswer> possibleAnswerList = new ArrayList<PossibleAnswer>(Arrays.asList($pas));
		possibleAnswerList.add(newAnswer);
		$mcq.setPossibleAnswers(possibleAnswerList.toArray());
		update( $mcq );		
end
