package org.tohu.generator
  
import org.tohu.Questionnaire;
import org.tohu.Group;
import org.tohu.Question;
import org.tohu.MultipleChoiceQuestion;

rule "MultiChoice_Conditional_Question_Add_itemID_row.rowNumber"
dialect "mvel"
	when
		$g : Group ( id == "groupID", items == null || items not contains "itemID" )
#		( or MultipleChoiceQuestion ( id == "questionID", answered == true, textAnswer == "condition" )
#			 Question ( id == "questionID", answered == true, textAnswer == "condition" ))
		Question ( id == "questionID", answered == true, textAnswer == "condition" )
	then
		MultipleChoiceQuestion question = new MultipleChoiceQuestion("itemID");
		question.setPreLabel("label");
		question.setAnswerType("text");
		question.setPresentationStyles({"style"});		
		insert(question);
		
		$g.appendItem( "itemID", "questionID" );
		update( $g );		
end

rule "MultiChoice_Conditional_Question_Retract_itemID_row.rowNumber"
dialect "mvel"
	when
		$g : Group ( id == "groupID", items != null && items contains "itemID" )
#		( or MultipleChoiceQuestion ( id == "questionID", answered == true, textAnswer != "condition" )
#			 Question ( id == "questionID", answered == true, textAnswer != "condition" ) )
		Question ( id == "questionID", answered == true, textAnswer != "condition" )
		$q : MultipleChoiceQuestion ( id == "itemID" )		      
	then		
		$g.removeItem( "itemID" );
		update( $g );		
		retract($q);
end
